- hosts: server
  become: yes
  
  vars_files:
    - /home/debian/vars.yml
    
  roles:
    - role: mount-disk
    - role: geerlingguy.java
 #  - role: andrewrothstein.miniconda
 #  - role: stefangweichinger.rclone
    - role: install-software
    - role: geerlingguy.docker
