- hosts: server
  become: yes
    
  roles:
    - role: mount-disk
    - role: geerlingguy.java
 #  - role: andrewrothstein.miniconda
 #  - role: stefangweichinger.rclone
    - role: install-software
    - role: geerlingguy.docker
